version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/walletdb
      - SPRING_DATASOURCE_USERNAME=walletuser
      - SPRING_DATASOURCE_PASSWORD=walletpassword
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: walletuser
      POSTGRES_PASSWORD: walletpassword
    ports:
      - "5432:5432"
